### ISSUE TITLE
it's not clear

### ISSUE THREAD

**Issue by maravento** [Busindre/viewDOS#1]
It is not clear, the procedure to use it or its operation. Could you be more specific? Thanks

**Comment by Busindre** [comment]
Hi.

Could you be more explicit? I have created an example of use in the README.md, I hope that helps.

Regards.

**Comment by maravento** [comment]
No explanation needed. Only practical examples of its use

**Comment by Busindre** [comment]
A practical example would be this:

Suppose you have a cluster composed of 20 web servers. Then you receive a denial of service attack and you want to obtain the IP addresses based on the state of the TCP connections (of the 20 nodes of the cluster) in a unified way to block them, make some notification, etc.
